/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package uimodels;

import controller.CheckoutController;

import javax.swing.JDialog;
import javax.swing.SwingUtilities;

/**
 *
 * @author abenitrust
 */
public class CheckoutRecordSearch extends javax.swing.JPanel implements Initializable {

    /**
     * Creates new form CheckoutRecordSearch
     */
    public CheckoutRecordSearch() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        memberId = new javax.swing.JTextField();
        searchRecordBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        jLabel1.setText("Member ID");

        searchRecordBtn.setText("Search Record");
        searchRecordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchRecordBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchRecordBtn)
                        .addGap(14, 14, 14)
                        .addComponent(cancelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(memberId, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGap(89, 89, 89))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(memberId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchRecordBtn)
                    .addComponent(cancelBtn))
                .addContainerGap(116, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchRecordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchRecordBtnActionPerformed
        try{
            CheckoutController.getInstance().getCheckoutRecord(memberId.getText());
            getMainWindow().switch_panel(new CheckoutRecord(memberId.getText()));
            closeParentDialog();
            
        } catch (Exception e) {
            getMainWindow().showErrorDialog(e.getMessage());
        }
        
    }//GEN-LAST:event_searchRecordBtnActionPerformed

    public MainWindow getMainWindow() {
       JDialog parentDialog = (JDialog)SwingUtilities.getWindowAncestor(this);
       return (MainWindow)SwingUtilities.getWindowAncestor(parentDialog); 
    }
    
    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        closeParentDialog();
    }//GEN-LAST:event_cancelBtnActionPerformed
                                                                             
    public void closeParentDialog() {
        SwingUtilities.windowForComponent(this).dispose();
    }
    
    
    public void onPanelVisible() {}
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField memberId;
    private javax.swing.JButton searchRecordBtn;
    // End of variables declaration//GEN-END:variables
}
