/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
        
import auth.AuthenticationManager;
import business.LibraryMember;
import business.Role;

/**
 *
 * @author abenitrust
 */
public class LandingPageP extends javax.swing.JPanel implements Initializable{

    /**
     * Creates new form LandingPageP
     */
    public LandingPageP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gotoMembers = new javax.swing.JButton();
        gotoBooks = new javax.swing.JButton();
        checoutBookBtn = new javax.swing.JButton();
        checkoutRecord = new javax.swing.JButton();
        name = new javax.swing.JLabel();
        role = new javax.swing.JLabel();
        logOut = new javax.swing.JButton();

        gotoMembers.setText("Members");
        gotoMembers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gotoMembersActionPerformed(evt);
            }
        });

        gotoBooks.setText("Books");
        gotoBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gotoBooksActionPerformed(evt);
            }
        });

        checoutBookBtn.setText("Checkout Book");
        checoutBookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checoutBookBtnActionPerformed(evt);
            }
        });

        checkoutRecord.setText("CheckoutRecord");
        checkoutRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutRecordActionPerformed(evt);
            }
        });

        name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name.setText("User");

        role.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        role.setText("Role");

        logOut.setText("Log out");
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(role, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(gotoMembers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gotoBooks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checoutBookBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkoutRecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(logOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(role)
                .addGap(33, 33, 33)
                .addComponent(name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(gotoBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(gotoMembers)
                .addGap(13, 13, 13)
                .addComponent(checoutBookBtn)
                .addGap(18, 18, 18)
                .addComponent(checkoutRecord)
                .addGap(18, 18, 18)
                .addComponent(logOut)
                .addContainerGap(83, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void gotoMembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gotoMembersActionPerformed
        MainWindow container = getMainWindow();
        container.switch_panel(container.getMemberListPage());
    }//GEN-LAST:event_gotoMembersActionPerformed

    private void gotoBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gotoBooksActionPerformed
        MainWindow container = getMainWindow();
        container.switch_panel(container.getBookListPage());
    }//GEN-LAST:event_gotoBooksActionPerformed

    private void checoutBookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checoutBookBtnActionPerformed
        JDialog jdl = new JDialog(getMainWindow(), "Checout Book", JDialog.ModalityType.DOCUMENT_MODAL);
        jdl.add(new Checkout());
        jdl.pack();
        jdl.setLocationRelativeTo(getMainWindow());
        jdl.show();
    }//GEN-LAST:event_checoutBookBtnActionPerformed

    private void checkoutRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutRecordActionPerformed
        JDialog jdl = new JDialog(getMainWindow(), "Checout Record", JDialog.ModalityType.DOCUMENT_MODAL);
        jdl.add(new CheckoutRecordSearch());
        jdl.pack();
        jdl.setLocationRelativeTo(getMainWindow());
        jdl.show();
    }//GEN-LAST:event_checkoutRecordActionPerformed

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        AuthenticationManager.INSTANCE.clearSession();
        getMainWindow().switch_panel(getMainWindow().getLoginPage());
    }//GEN-LAST:event_logOutActionPerformed

   
    
    
    private MainWindow getMainWindow() {
        return (MainWindow)SwingUtilities.getWindowAncestor(this);
    }
    
    public void setMemberDetails() {
        LibraryMember loggedUser = AuthenticationManager.INSTANCE.getUser();
        setMemberName(loggedUser.getFirstName());
        setMemberRole(loggedUser.getRole().name());
    }
    
    private void setMemberName(String name) {
        this.name.setText("Welcom " + name);
    }
    
    private void setMemberRole(String role) {
        this.role.setText(role);
    }
    
    public void updateBtnVisiblityByRole() {
        Role memberRole = AuthenticationManager.INSTANCE.getUser().getRole();
        switch(memberRole) {
            case ADMIN:
                checoutBookBtn.setVisible(false);
                gotoBooks.setVisible(true);
                checkoutRecord.setVisible(true);
                gotoMembers.setVisible(true);
                break;
            case LIBRARIAN:
                checoutBookBtn.setVisible(true);
                gotoBooks.setVisible(true);
                checkoutRecord.setVisible(true);
                gotoMembers.setVisible(false);
                getMainWindow().getMembersMenu().setVisible(false);
                break;
            case BOTH:
                checoutBookBtn.setVisible(true);
                gotoBooks.setVisible(true);
                checkoutRecord.setVisible(true);
                gotoMembers.setVisible(true);
                getMainWindow().getMembersMenu().setVisible(true);
                break;
            default:
                break;
        }
    }
    
    public void onPanelVisible() {
        setMemberDetails();
        updateBtnVisiblityByRole();
        getMainWindow().getHomeMenu().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkoutRecord;
    private javax.swing.JButton checoutBookBtn;
    private javax.swing.JButton gotoBooks;
    private javax.swing.JButton gotoMembers;
    private javax.swing.JButton logOut;
    private javax.swing.JLabel name;
    private javax.swing.JLabel role;
    // End of variables declaration//GEN-END:variables
    
    
}
